export const MARD_PALETTE = [
  { code: "A1", name: "奶油白", hex: "#F8F6ED" },
  { code: "A2", name: "米白", hex: "#F1E7D1" },
  { code: "A3", name: "浅杏", hex: "#F7DCAE" },
  { code: "A4", name: "蜜桃", hex: "#F6C48F" },
  { code: "A5", name: "金杏", hex: "#F4B15D" },
  { code: "A6", name: "亮黄", hex: "#F8C843" },
  { code: "A7", name: "南瓜橙", hex: "#EF9A36" },
  { code: "A8", name: "焦糖橙", hex: "#D6762D" },

  { code: "B1", name: "薄荷白", hex: "#EDF8F0" },
  { code: "B2", name: "浅豆绿", hex: "#CFE8B8" },
  { code: "B3", name: "嫩草绿", hex: "#A8DA77" },
  { code: "B4", name: "果冻绿", hex: "#81CA5D" },
  { code: "B5", name: "叶绿", hex: "#5EB247" },
  { code: "B6", name: "深草绿", hex: "#3C9440" },
  { code: "B7", name: "橄榄绿", hex: "#6C8E3A" },
  { code: "B8", name: "牌子绿", hex: "#18A54B" },

  { code: "C1", name: "冰白蓝", hex: "#EEF7FB" },
  { code: "C2", name: "浅雾蓝", hex: "#D7EBF7" },
  { code: "C3", name: "湖水蓝", hex: "#9CD6F3" },
  { code: "C4", name: "晴空蓝", hex: "#56B9EC" },
  { code: "C5", name: "天空蓝", hex: "#1E9DE2" },
  { code: "C6", name: "宝石蓝", hex: "#2F7FCC" },
  { code: "C7", name: "海军蓝", hex: "#2B5AA3" },
  { code: "C8", name: "深夜蓝", hex: "#213B75" },

  { code: "D1", name: "雾紫", hex: "#ECE3F7" },
  { code: "D2", name: "浅丁香", hex: "#D7C4F1" },
  { code: "D3", name: "葡萄紫", hex: "#B693E0" },
  { code: "D4", name: "薰衣草紫", hex: "#9A72CB" },
  { code: "D5", name: "莓果紫", hex: "#7B58AF" },
  { code: "D6", name: "暗紫", hex: "#5F448C" },
  { code: "D7", name: "李子紫", hex: "#4A336F" },
  { code: "D8", name: "墨紫", hex: "#32244B" },

  { code: "E1", name: "雪粉", hex: "#FBE9EF" },
  { code: "E2", name: "浅樱粉", hex: "#F6C8D8" },
  { code: "E3", name: "糖果粉", hex: "#F19DB8" },
  { code: "E4", name: "玫瑰粉", hex: "#EA769F" },
  { code: "E5", name: "洋红粉", hex: "#D65687" },
  { code: "E6", name: "莓果红", hex: "#B5416A" },
  { code: "E7", name: "酒红粉", hex: "#8D2F55" },
  { code: "E8", name: "暗莓紫", hex: "#64213D" },

  { code: "F1", name: "珊瑚白", hex: "#FBE5DE" },
  { code: "F2", name: "浅珊瑚", hex: "#F5BAA7" },
  { code: "F3", name: "桃红", hex: "#EF8F79" },
  { code: "F4", name: "暖红", hex: "#EA6553" },
  { code: "F5", name: "正红", hex: "#DF4039" },
  { code: "F6", name: "砖红", hex: "#C3312B" },
  { code: "F7", name: "绯红", hex: "#A91E2F" },
  { code: "F8", name: "枣红", hex: "#7A1723" },

  { code: "G1", name: "浅肤", hex: "#F7E5CF" },
  { code: "G2", name: "肤粉", hex: "#F2D2B2" },
  { code: "G3", name: "暖肤", hex: "#E8BC8E" },
  { code: "G4", name: "蜜糖肤", hex: "#D9A36F" },
  { code: "G5", name: "浅咖", hex: "#B98359" },
  { code: "G6", name: "奶咖", hex: "#9A6F49" },
  { code: "G7", name: "可可棕", hex: "#724B33" },
  { code: "G8", name: "深可可", hex: "#5B3929" },

  { code: "H1", name: "纯白", hex: "#FFFFFF" },
  { code: "H2", name: "暖灰", hex: "#E9E3DB" },
  { code: "H3", name: "浅灰", hex: "#CACBD0" },
  { code: "H4", name: "中灰", hex: "#9AA0AC" },
  { code: "H5", name: "石墨灰", hex: "#707683" },
  { code: "H6", name: "深灰", hex: "#4A4F58" },
  { code: "H7", name: "纯黑", hex: "#111111" },
  { code: "H8", name: "炭黑", hex: "#202224" }
];
